import BigExecBrand from './components/BigExecBrand';

const pillars=[['01','BUILD','Create a franchise identity that survives beyond a single matchup.'],['02','COMMAND','Draft, trade, set the lineup, and control the room.'],['03','BECOME LEGENDARY','Turn rivalries, championships, and weekly moments into permanent history.']];

export default function HomePage(){return <main className="brandSiteShell">
  <section className="brandHero"><div className="brandHeroShade" aria-hidden="true"/><header className="brandSiteHeader"><BigExecBrand/><nav aria-label="Public navigation"><a href="#experience">The Experience</a><a href="#franchise">Franchise Legacy</a><a className="headerSignIn" href="/login">Sign In</a></nav></header>
    <div className="brandHeroContent"><p className="brandKicker">THE FRONT OFFICE IS YOURS</p><h1>Don’t just play fantasy.<br/><em>Run the franchise.</em></h1><p>Draft the roster. Command the room. Build a stadium that remembers every rivalry, every upset, and every championship.</p><div className="brandHeroActions"><a className="brandButton gold" href="/login?mode=signup&role=commissioner">Create Your Front Office</a><a className="brandButton glass" href="/login">Enter Big Exec</a></div><div className="brandProof"><span><b>PRO FOOTBALL</b>Launching first</span><span><b>FRANCHISE LEGACY</b>Built to persist</span><span><b>ARCADE RECAPS</b>Your season, cinematic</span></div></div><div className="scrollCue" aria-hidden="true">EXPLORE <i/></div>
  </section>
  <section className="brandManifesto" id="experience"><p>EVERYBODY DRAFTS.</p><h2>Big Execs build franchises.</h2><div className="manifestoGrid">{pillars.map(([number,title,copy])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="franchiseFeature" id="franchise"><div className="franchiseFeatureCopy"><p className="brandKicker">YOUR HOUSE. YOUR COLORS. YOUR HISTORY.</p><h2>A stadium that earns its story.</h2><p>Every new franchise begins with a real home. Achievements unlock monuments, banners, and permanent upgrades in your colors—turning a fantasy team into a place worth returning to.</p><a className="brandButton gold" href="/login?mode=signup">Start Building</a></div><div className="franchiseFeatureVisual" role="img" aria-label="A vivid Big Exec franchise stadium illuminated at night"><div><span>STARTER STADIUM</span><strong>YOUR LEGACY<br/>STARTS HERE.</strong></div></div></section>
  <footer className="brandFooter"><BigExecBrand compact/><p>Run the franchise. Own the season.</p><a href="/login?mode=signup">Create account →</a></footer>
  </main>}
