function esc(value: string) {
  return value.replace(/[&<>"']/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[character] ?? character));
}

function shell(eyebrow: string, heading: string, body: string, ctaLabel: string, ctaUrl: string) {
  return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f4f1e8;color:#171717;font-family:Arial,Helvetica,sans-serif"><div role="article" aria-label="Big Exec Fantasy Sports email" style="max-width:620px;margin:0 auto;padding:32px 20px"><div style="background:#ffffff;border:1px solid #d8d3c7;padding:28px"><div style="border-bottom:1px solid #c8c2b6;padding-bottom:18px;margin-bottom:28px"><div style="font-size:28px;line-height:1;font-weight:900;letter-spacing:-1px;color:#111111">BIG EXEC</div><div style="font-size:11px;font-weight:800;letter-spacing:3px;color:#7a5a00;margin-top:6px">FANTASY SPORTS</div></div><div style="font-size:12px;font-weight:800;letter-spacing:1.6px;color:#7a5a00;margin-bottom:16px">${esc(eyebrow)}</div><h1 style="font-size:40px;line-height:1.02;text-transform:uppercase;margin:0 0 22px;color:#111111">${esc(heading)}</h1><div style="font-size:17px;line-height:1.65;color:#2a2a2a">${body}</div><div style="margin:30px 0"><a href="${esc(ctaUrl)}" aria-label="${esc(ctaLabel)}" style="display:inline-block;background:#D4AF37;color:#111111;text-decoration:none;padding:16px 20px;font-size:14px;font-weight:900;letter-spacing:.5px;border:2px solid #8a6b13">${esc(ctaLabel)}</a></div><div style="border-top:1px solid #c8c2b6;padding-top:18px;color:#333333;font-size:13px;line-height:1.6">Run the franchise. Own the season.<br><br>If the button does not work, copy this link into your browser:<br><span style="word-break:break-all;color:#111111">${esc(ctaUrl)}</span></div></div></div></body></html>`;
}

export function leagueInviteEmail(input: { leagueName:string; commissionerName:string; seasonLabel:string; claimedCount:number; totalSpots:number; claimUrl:string; expiresLabel:string; }) {
  const body = `<p style="margin:0 0 14px">${esc(input.commissionerName)} saved you a franchise spot in <strong style="color:#111111">${esc(input.leagueName)}</strong> on Big Exec Fantasy Sports.</p><p style="margin:0 0 14px">Claim it, name your franchise, choose your colors, and start building a record that can follow you season after season.</p><p style="margin:22px 0 0;color:#111111"><strong>Pro Football • Half-PPR</strong><br>${input.claimedCount}/${input.totalSpots} franchise spots claimed<br>${esc(input.seasonLabel)} season</p><p style="margin:14px 0 0;font-size:14px;color:#333333">Invitation expires ${esc(input.expiresLabel)}.</p>`;
  const text = `BIG EXEC FANTASY SPORTS\n\nYou've been drafted into the league.\n\nJoin ${input.leagueName}\n\n${input.commissionerName} saved you a franchise spot in ${input.leagueName} on Big Exec Fantasy Sports.\n\nClaim it, name your franchise, choose your colors, and start building a record that can follow you season after season.\n\nPro Football • Half-PPR\n${input.claimedCount}/${input.totalSpots} franchise spots claimed\n${input.seasonLabel} season\n\nInvitation expires ${input.expiresLabel}.\n\nClaim your franchise: ${input.claimUrl}\n\nRun the franchise. Own the season.`;
  return { subject:`Big Exec invite: ${input.leagueName}`, html:shell("YOU'VE BEEN DRAFTED INTO THE LEAGUE.",`Join ${input.leagueName}`,body,'CLAIM MY FRANCHISE',input.claimUrl), text };
}

export function draftAnnouncementEmail(input:{leagueName:string;draftLabel:string;draftUrl:string}) {
  const body=`<p>Draft Day is officially on the calendar for <strong style="color:#111111">${esc(input.leagueName)}</strong>.</p><p style="color:#111111"><strong>${esc(input.draftLabel)}</strong></p><p>Check your franchise, review the player pool, and be ready when the clock starts.</p>`;
  const text=`BIG EXEC FANTASY SPORTS\n\nDraft Day\n\nThe clock is coming.\n\nDraft Day is officially on the calendar for ${input.leagueName}.\n${input.draftLabel}\n\nPrep for the draft: ${input.draftUrl}`;
  return { subject:`Big Exec Draft Day: ${input.leagueName}`,html:shell('DRAFT DAY', 'The clock is coming.',body,'PREP FOR THE DRAFT',input.draftUrl),text };
}

export function matchupFinalEmail(input:{franchiseName:string;opponentName:string;yourScore:string;opponentScore:string;resultLabel:string;storyLine:string;recapUrl:string}) {
  const body=`<p style="font-size:13px;letter-spacing:1px;color:#333333">${esc(input.resultLabel)}</p><p style="font-size:24px;color:#111111"><strong>${esc(input.franchiseName)} ${esc(input.yourScore)}</strong><br>${esc(input.opponentName)} ${esc(input.opponentScore)}</p><p>${esc(input.storyLine)}</p>`;
  const text=`BIG EXEC FANTASY SPORTS\n\nMatchup Final\n\n${input.resultLabel}\n${input.franchiseName} ${input.yourScore}\n${input.opponentName} ${input.opponentScore}\n\n${input.storyLine}\n\nWatch the recap: ${input.recapUrl}`;
  return { subject:`Big Exec FINAL: ${input.franchiseName} ${input.yourScore} — ${input.opponentScore} ${input.opponentName}`,html:shell('MATCHUP FINAL','The result is in.',body,'WATCH THE RECAP',input.recapUrl),text };
}
