function esc(value: string) {
  return value.replace(/[&<>"']/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[character] ?? character));
}

function shell(eyebrow: string, heading: string, body: string, ctaLabel: string, ctaUrl: string) {
  return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"></head><body style="margin:0;background:#030405;color:#f7f4ed;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#030405"><tr><td align="center" style="padding:32px 14px"><table role="article" aria-label="Big Exec Fantasy Sports email" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;border:1px solid #5a451b;background:#0a0c10"><tr><td style="height:7px;background:#d8a62c"></td></tr><tr><td align="center" style="padding:28px 28px 24px;border-bottom:1px solid #332b1c"><img src="https://bigexecfs.com/brand/big-exec-approved-wordmark-v1.png" width="360" alt="Big Exec Fantasy Sports" style="display:block;width:100%;max-width:360px;height:auto"></td></tr><tr><td style="padding:42px 34px 36px;background:radial-gradient(circle at 90% 0,#241b09,#0a0c10 42%)"><div style="font-size:11px;font-weight:900;letter-spacing:2.4px;color:#e7b43b;margin-bottom:18px">${esc(eyebrow)}</div><h1 style="font-size:42px;line-height:1;text-transform:uppercase;margin:0 0 24px;color:#f7f4ed;letter-spacing:-1.5px">${esc(heading)}</h1><div style="font-size:16px;line-height:1.7;color:#c9c5bb">${body}</div><div style="margin:34px 0 6px"><a href="${esc(ctaUrl)}" aria-label="${esc(ctaLabel)}" style="display:inline-block;background:#e0aa2e;color:#070707;text-decoration:none;padding:17px 24px;font-size:13px;font-weight:900;letter-spacing:1px;border:1px solid #ffdb71">${esc(ctaLabel)}</a></div></td></tr><tr><td style="padding:24px 34px;border-top:1px solid #332b1c;background:#060709;color:#85837d;font-size:12px;line-height:1.7"><strong style="color:#e4b13a;letter-spacing:1.4px">RUN THE FRANCHISE. OWN THE SEASON.</strong><br><br>If the button does not work, copy this link:<br><span style="word-break:break-all;color:#bdb9af">${esc(ctaUrl)}</span></td></tr></table></td></tr></table></body></html>`;
}

export function leagueInviteEmail(input: { leagueName:string; commissionerName:string; seasonLabel:string; claimedCount:number; totalSpots:number; claimUrl:string; expiresLabel:string; }) {
  const body = `<p style="margin:0 0 14px">${esc(input.commissionerName)} saved you a franchise spot in <strong style="color:#f7f4ed">${esc(input.leagueName)}</strong>.</p><p style="margin:0 0 14px">Claim it, name your franchise, choose your colors, and start building a record that follows you season after season.</p><p style="margin:24px 0 0;padding:16px;border-left:3px solid #d8a62c;background:#111318;color:#f7f4ed"><strong>PRO FOOTBALL • HALF-PPR</strong><br>${input.claimedCount}/${input.totalSpots} franchise spots claimed<br>${esc(input.seasonLabel)} season</p><p style="margin:14px 0 0;font-size:13px;color:#8f8d87">Invitation expires ${esc(input.expiresLabel)}.</p>`;
  const text = `BIG EXEC FANTASY SPORTS\n\nYou've been drafted into the league.\n\nJoin ${input.leagueName}\n\n${input.commissionerName} saved you a franchise spot in ${input.leagueName} on Big Exec Fantasy Sports.\n\nClaim it, name your franchise, choose your colors, and start building a record that can follow you season after season.\n\nPro Football • Half-PPR\n${input.claimedCount}/${input.totalSpots} franchise spots claimed\n${input.seasonLabel} season\n\nInvitation expires ${input.expiresLabel}.\n\nClaim your franchise: ${input.claimUrl}\n\nRun the franchise. Own the season.`;
  return { subject:`Big Exec invite: ${input.leagueName}`, html:shell("YOU'VE BEEN DRAFTED INTO THE LEAGUE.",`Join ${input.leagueName}`,body,'CLAIM MY FRANCHISE',input.claimUrl), text };
}

export function draftAnnouncementEmail(input:{leagueName:string;draftLabel:string;draftUrl:string}) {
  const body=`<p>Draft Day is officially on the calendar for <strong style="color:#f7f4ed">${esc(input.leagueName)}</strong>.</p><p style="padding:16px;border-left:3px solid #d8a62c;background:#111318;color:#f7f4ed"><strong>${esc(input.draftLabel)}</strong></p><p>Check your franchise, review the player pool, and be ready when the clock starts.</p>`;
  const text=`BIG EXEC FANTASY SPORTS\n\nDraft Day\n\nThe clock is coming.\n\nDraft Day is officially on the calendar for ${input.leagueName}.\n${input.draftLabel}\n\nPrep for the draft: ${input.draftUrl}`;
  return { subject:`Big Exec Draft Day: ${input.leagueName}`,html:shell('DRAFT DAY', 'The clock is coming.',body,'PREP FOR THE DRAFT',input.draftUrl),text };
}

export function matchupFinalEmail(input:{franchiseName:string;opponentName:string;yourScore:string;opponentScore:string;resultLabel:string;storyLine:string;recapUrl:string}) {
  const body=`<p style="font-size:12px;letter-spacing:1.5px;color:#e2ac32">${esc(input.resultLabel)}</p><p style="font-size:24px;line-height:1.5;color:#f7f4ed"><strong>${esc(input.franchiseName)} ${esc(input.yourScore)}</strong><br><span style="color:#aaa69d">${esc(input.opponentName)} ${esc(input.opponentScore)}</span></p><p>${esc(input.storyLine)}</p>`;
  const text=`BIG EXEC FANTASY SPORTS\n\nMatchup Final\n\n${input.resultLabel}\n${input.franchiseName} ${input.yourScore}\n${input.opponentName} ${input.opponentScore}\n\n${input.storyLine}\n\nWatch the recap: ${input.recapUrl}`;
  return { subject:`Big Exec FINAL: ${input.franchiseName} ${input.yourScore} — ${input.opponentScore} ${input.opponentName}`,html:shell('MATCHUP FINAL','The result is in.',body,'WATCH THE RECAP',input.recapUrl),text };
}
