-- RECOVERED from supabase_migrations.schema_migrations.statements (production history).
-- version 20260820043923, name core_foundation. Retrieved 2026-10-04T04:56:57Z (UTC).
-- Already applied in production. Kept for the record only; do NOT re-apply.

create extension if not exists pgcrypto;
create type sport_code as enum ('football','basketball','baseball','soccer');
create type competition_level as enum ('pro','college');
create type member_role as enum ('commissioner','manager');
create type lineup_slot as enum ('QB','RB','WR','TE','FLEX','K','DST','BENCH','IR');
create type game_state as enum ('scheduled','in_progress','final','postponed','canceled','delayed','suspended','unknown');
create table sports (id uuid primary key default gen_random_uuid(),code sport_code not null unique,display_name text not null);
create table competitions (id uuid primary key default gen_random_uuid(),sport_id uuid not null references sports(id),level competition_level not null,gender text,code text not null unique,display_name text not null,active boolean not null default true);
create table competition_seasons (id uuid primary key default gen_random_uuid(),competition_id uuid not null references competitions(id),season_year int not null,starts_on date,ends_on date,unique (competition_id, season_year));
create table real_teams (id uuid primary key default gen_random_uuid(),competition_id uuid not null references competitions(id),display_name text not null,abbreviation text,active boolean not null default true);
create table athletes (id uuid primary key default gen_random_uuid(),competition_id uuid not null references competitions(id),real_team_id uuid references real_teams(id),display_name text not null,position text not null,active boolean not null default true,injury_status text,updated_at timestamptz not null default now());
create table athlete_provider_ids (athlete_id uuid not null references athletes(id) on delete cascade,provider text not null,provider_athlete_id text not null,primary key (provider, provider_athlete_id),unique (athlete_id, provider));
create table real_games (id uuid primary key default gen_random_uuid(),competition_season_id uuid not null references competition_seasons(id),provider_game_id text,week int,home_team_id uuid references real_teams(id),away_team_id uuid references real_teams(id),starts_at timestamptz not null,state game_state not null default 'scheduled',home_score int,away_score int,updated_at timestamptz not null default now());
create table athlete_game_stats (id uuid primary key default gen_random_uuid(),athlete_id uuid not null references athletes(id),game_id uuid not null references real_games(id),raw_stats jsonb not null default '{}'::jsonb,source_provider text not null,source_updated_at timestamptz,ingested_at timestamptz not null default now(),unique (athlete_id, game_id, source_provider));
create table fantasy_leagues (id uuid primary key default gen_random_uuid(),name text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table league_seasons (id uuid primary key default gen_random_uuid(),league_id uuid not null references fantasy_leagues(id) on delete cascade,competition_season_id uuid not null references competition_seasons(id),status text not null default 'setup',roster_config jsonb not null,scoring_profile_id uuid,unique (league_id, competition_season_id));
create table league_members (id uuid primary key default gen_random_uuid(),league_id uuid not null references fantasy_leagues(id) on delete cascade,user_id uuid not null references auth.users(id),role member_role not null default 'manager',joined_at timestamptz not null default now(),unique (league_id, user_id));
create table franchises (id uuid primary key default gen_random_uuid(),league_id uuid not null references fantasy_leagues(id) on delete cascade,name text not null,abbreviation text,primary_color text,secondary_color text,established_year int not null,created_at timestamptz not null default now(),unique (league_id, name));
create table franchise_owners (franchise_id uuid not null references franchises(id) on delete cascade,user_id uuid not null references auth.users(id),starts_on date not null default current_date,ends_on date,primary key (franchise_id, user_id, starts_on));
create table season_franchises (id uuid primary key default gen_random_uuid(),league_season_id uuid not null references league_seasons(id) on delete cascade,franchise_id uuid not null references franchises(id) on delete cascade,draft_position int,unique (league_season_id, franchise_id));
create table scoring_profiles (id uuid primary key default gen_random_uuid(),name text not null,sport sport_code not null,rules jsonb not null,is_system_default boolean not null default false);
alter table league_seasons add constraint league_seasons_scoring_profile_fk foreign key (scoring_profile_id) references scoring_profiles(id);
create table roster_entries (id uuid primary key default gen_random_uuid(),season_franchise_id uuid not null references season_franchises(id) on delete cascade,athlete_id uuid not null references athletes(id),acquired_via text not null,added_at timestamptz not null default now(),dropped_at timestamptz,unique (season_franchise_id, athlete_id, added_at));
create table lineups (id uuid primary key default gen_random_uuid(),season_franchise_id uuid not null references season_franchises(id) on delete cascade,week int not null,athlete_id uuid not null references athletes(id),slot lineup_slot not null,locked_at timestamptz,unique (season_franchise_id, week, athlete_id),unique (season_franchise_id, week, slot, athlete_id));
create table fantasy_player_scores (id uuid primary key default gen_random_uuid(),league_season_id uuid not null references league_seasons(id) on delete cascade,athlete_id uuid not null references athletes(id),game_id uuid not null references real_games(id),week int not null,points numeric(8,2) not null,breakdown jsonb not null,calculated_at timestamptz not null default now(),unique (league_season_id, athlete_id, game_id));
create table matchups (id uuid primary key default gen_random_uuid(),league_season_id uuid not null references league_seasons(id) on delete cascade,week int not null,home_season_franchise_id uuid not null references season_franchises(id),away_season_franchise_id uuid not null references season_franchises(id),event_type text not null default 'circuit',home_points numeric(8,2) not null default 0,away_points numeric(8,2) not null default 0,winner_season_franchise_id uuid references season_franchises(id),is_final boolean not null default false,unique (league_season_id, week, home_season_franchise_id),unique (league_season_id, week, away_season_franchise_id));
create table standings (league_season_id uuid not null references league_seasons(id) on delete cascade,season_franchise_id uuid not null references season_franchises(id) on delete cascade,wins int not null default 0,losses int not null default 0,ties int not null default 0,points_for numeric(10,2) not null default 0,points_against numeric(10,2) not null default 0,streak int not null default 0,primary key (league_season_id, season_franchise_id));
create table league_feed_events (id uuid primary key default gen_random_uuid(),league_id uuid not null references fantasy_leagues(id) on delete cascade,season_id uuid references league_seasons(id) on delete cascade,actor_user_id uuid references auth.users(id),event_type text not null,body text,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
insert into sports(code, display_name) values ('football','Football'),('basketball','Basketball'),('baseball','Baseball'),('soccer','Soccer') on conflict do nothing;
insert into competitions(sport_id, level, gender, code, display_name)
select s.id, 'pro'::competition_level, null, 'pro_football', 'Pro Football' from sports s where s.code='football'
union all select s.id, 'college'::competition_level, null, 'college_football', 'College Football' from sports s where s.code='football'
union all select s.id, 'pro'::competition_level, 'men', 'mens_pro_basketball', 'Men''s Pro Basketball' from sports s where s.code='basketball'
union all select s.id, 'pro'::competition_level, 'women', 'womens_pro_basketball', 'Women''s Pro Basketball' from sports s where s.code='basketball'
union all select s.id, 'college'::competition_level, 'men', 'mens_college_basketball', 'Men''s College Basketball' from sports s where s.code='basketball'
union all select s.id, 'college'::competition_level, 'women', 'womens_college_basketball', 'Women''s College Basketball' from sports s where s.code='basketball'
union all select s.id, 'pro'::competition_level, null, 'pro_baseball', 'Pro Baseball' from sports s where s.code='baseball'
union all select s.id, 'pro'::competition_level, 'men', 'mens_soccer', 'Men''s Soccer' from sports s where s.code='soccer'
union all select s.id, 'pro'::competition_level, 'women', 'womens_soccer', 'Women''s Soccer' from sports s where s.code='soccer' on conflict (code) do nothing;
alter table fantasy_leagues enable row level security; alter table league_members enable row level security; alter table franchises enable row level security; alter table league_seasons enable row level security; alter table league_feed_events enable row level security;
create policy league_member_read_leagues on fantasy_leagues for select using (created_by = auth.uid() or exists(select 1 from league_members lm where lm.league_id=id and lm.user_id=auth.uid()));
create policy league_member_read_members on league_members for select using (exists(select 1 from league_members me where me.league_id=league_members.league_id and me.user_id=auth.uid()));
create policy league_member_read_franchises on franchises for select using (exists(select 1 from league_members me where me.league_id=franchises.league_id and me.user_id=auth.uid()));
create policy league_member_read_seasons on league_seasons for select using (exists(select 1 from league_members me where me.league_id=league_seasons.league_id and me.user_id=auth.uid()));
create policy league_member_read_feed on league_feed_events for select using (exists(select 1 from league_members me where me.league_id=league_feed_events.league_id and me.user_id=auth.uid()));
