-- RECOVERED from supabase_migrations.schema_migrations.statements (production history).
-- version 20260820044246, name season_one_gameplay. Retrieved 2026-10-04T04:56:57Z (UTC).
-- Already applied in production. Kept for the record only; do NOT re-apply.

create table user_profiles (user_id uuid primary key references auth.users(id) on delete cascade,display_name text,avatar_key text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table league_invites (id uuid primary key default gen_random_uuid(),league_id uuid not null references fantasy_leagues(id) on delete cascade,invited_by uuid not null references auth.users(id),email text,invite_token uuid not null default gen_random_uuid() unique,status text not null default 'pending' check(status in('pending','accepted','revoked','expired')),expires_at timestamptz not null default(now()+interval '14 days'),accepted_by uuid references auth.users(id),accepted_at timestamptz,created_at timestamptz not null default now());
create table drafts (id uuid primary key default gen_random_uuid(),league_season_id uuid not null unique references league_seasons(id) on delete cascade,status text not null default 'scheduled' check(status in('scheduled','live','paused','complete')),draft_type text not null default 'snake' check(draft_type in('snake')),rounds int not null default 15,pick_seconds int not null default 90,current_pick int not null default 0,starts_at timestamptz,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table draft_picks (id uuid primary key default gen_random_uuid(),draft_id uuid not null references drafts(id) on delete cascade,pick_number int not null,round_number int not null,round_pick int not null,season_franchise_id uuid not null references season_franchises(id),athlete_id uuid references athletes(id),real_team_id uuid references real_teams(id),is_auto_pick boolean not null default false,picked_at timestamptz,check(((athlete_id is not null)::int+(real_team_id is not null)::int)<=1),unique(draft_id,pick_number));
create table trades (id uuid primary key default gen_random_uuid(),league_season_id uuid not null references league_seasons(id) on delete cascade,proposed_by_franchise_id uuid not null references season_franchises(id),proposed_to_franchise_id uuid not null references season_franchises(id),status text not null default 'proposed' check(status in('proposed','countered','accepted','rejected','canceled','expired')),created_at timestamptz not null default now(),resolved_at timestamptz);
create table trade_items (id uuid primary key default gen_random_uuid(),trade_id uuid not null references trades(id) on delete cascade,from_season_franchise_id uuid not null references season_franchises(id),to_season_franchise_id uuid not null references season_franchises(id),athlete_id uuid references athletes(id),real_team_id uuid references real_teams(id),check(((athlete_id is not null)::int+(real_team_id is not null)::int)=1));
create table trade_messages (id uuid primary key default gen_random_uuid(),trade_id uuid not null references trades(id) on delete cascade,user_id uuid not null references auth.users(id),body text not null check(char_length(body)<=2000),created_at timestamptz not null default now());
create table achievements (id uuid primary key default gen_random_uuid(),code text not null unique,display_name text not null,description text,category text not null,unlock_rule jsonb not null default '{}'::jsonb,active boolean not null default true);
create table franchise_achievements (id uuid primary key default gen_random_uuid(),franchise_id uuid not null references franchises(id) on delete cascade,league_season_id uuid references league_seasons(id) on delete set null,achievement_id uuid not null references achievements(id),week int,earned_at timestamptz not null default now(),payload jsonb not null default '{}'::jsonb);
create table stadiums (id uuid primary key default gen_random_uuid(),franchise_id uuid not null unique references franchises(id) on delete cascade,environment_key text not null default 'starter',created_at timestamptz not null default now());
create table stadium_features (id uuid primary key default gen_random_uuid(),code text not null unique,display_name text not null,zone text not null check(zone in('exterior','field','rafters','entrance')),achievement_code text,asset_key text,active boolean not null default true);
create table franchise_stadium_features (stadium_id uuid not null references stadiums(id) on delete cascade,stadium_feature_id uuid not null references stadium_features(id),unlocked_at timestamptz not null default now(),source_achievement_id uuid references franchise_achievements(id),primary key(stadium_id,stadium_feature_id));
create index draft_picks_draft_pick_idx on draft_picks(draft_id,pick_number); create index league_invites_token_idx on league_invites(invite_token); create index trades_season_status_idx on trades(league_season_id,status); create index franchise_achievements_franchise_idx on franchise_achievements(franchise_id,earned_at desc);
alter table user_profiles enable row level security; alter table league_invites enable row level security; alter table drafts enable row level security; alter table draft_picks enable row level security; alter table trades enable row level security; alter table trade_items enable row level security; alter table trade_messages enable row level security; alter table achievements enable row level security; alter table franchise_achievements enable row level security; alter table stadiums enable row level security; alter table stadium_features enable row level security; alter table franchise_stadium_features enable row level security;
create policy profile_read_authenticated on user_profiles for select to authenticated using(true); create policy profile_manage_self on user_profiles for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy member_read_drafts on drafts for select to authenticated using(exists(select 1 from league_seasons ls where ls.id=league_season_id and public.is_league_member(ls.league_id))); create policy member_read_draft_picks on draft_picks for select to authenticated using(exists(select 1 from drafts d join league_seasons ls on ls.id=d.league_season_id where d.id=draft_id and public.is_league_member(ls.league_id)));
create policy member_read_trades on trades for select to authenticated using(exists(select 1 from league_seasons ls where ls.id=league_season_id and public.is_league_member(ls.league_id))); create policy member_read_trade_items on trade_items for select to authenticated using(exists(select 1 from trades t join league_seasons ls on ls.id=t.league_season_id where t.id=trade_id and public.is_league_member(ls.league_id)));
create policy trade_participant_read_messages on trade_messages for select to authenticated using(exists(select 1 from trades t join season_franchises a on a.id=t.proposed_by_franchise_id join season_franchises b on b.id=t.proposed_to_franchise_id join franchise_owners fa on fa.franchise_id=a.franchise_id join franchise_owners fb on fb.franchise_id=b.franchise_id where t.id=trade_id and ((fa.user_id=auth.uid() and fa.ends_on is null) or (fb.user_id=auth.uid() and fb.ends_on is null))));
create policy authenticated_read_achievements on achievements for select to authenticated using(true); create policy authenticated_read_stadium_features on stadium_features for select to authenticated using(true); create policy member_read_franchise_achievements on franchise_achievements for select to authenticated using(exists(select 1 from franchises f where f.id=franchise_id and public.is_league_member(f.league_id))); create policy member_read_stadiums on stadiums for select to authenticated using(exists(select 1 from franchises f where f.id=franchise_id and public.is_league_member(f.league_id))); create policy member_read_franchise_stadium_features on franchise_stadium_features for select to authenticated using(exists(select 1 from stadiums s join franchises f on f.id=s.franchise_id where s.id=stadium_id and public.is_league_member(f.league_id)));
insert into achievements(code,display_name,description,category) values('FIRST_WIN','First Win','Win the first matchup in franchise history.','milestone'),('RIVALRY_WIN','Rivalry Win','Win a Rivalry Week matchup.','rivalry'),('REVENGE_COMPLETE','Revenge Complete','Win a designated Revenge Week rematch.','revenge'),('LEAGUE_CHAMPION','League Champion','Win the league championship.','championship'),('GIANT_KILLER','Giant Killer','Defeat a substantially higher-ranked franchise during a qualifying event.','weekly') on conflict(code) do nothing;
insert into stadium_features(code,display_name,zone,achievement_code,asset_key) values('FIRST_WIN_FLAG','Franchise Victory Flag','exterior','FIRST_WIN','stadium/first-win-flag'),('RIVALRY_MONUMENT','Rivalry Monument','exterior','RIVALRY_WIN','stadium/rivalry-monument'),('CHAMPIONSHIP_BANNER','Championship Banner','rafters','LEAGUE_CHAMPION','stadium/championship-banner') on conflict(code) do nothing;
