import { signIn, signUp } from '../auth/actions';
import BigExecBrand from '../components/BigExecBrand';

export default async function LoginPage({searchParams}:{searchParams:Promise<{error?:string;message?:string;next?:string;mode?:string}>}){
  const params=await searchParams; const next=params.next?.startsWith('/')&&!params.next.startsWith('//')?params.next:'/dashboard'; const isSignup=params.mode==='signup'; const encodedNext=encodeURIComponent(next);
  return <main className="accessShell"><section className="accessScene"><a className="accessBack" href="/">← Back to Big Exec</a><BigExecBrand/><div className="accessSceneCopy"><p className="brandKicker">{isSignup?'YOUR LEGACY STARTS HERE':'WELCOME BACK, EXEC'}</p><h1>{isSignup?'Build something legendary.':'The front office is waiting.'}</h1><p>{isSignup?'One identity. Every league. A franchise history designed to outlive the week.':'Your lineup, league, stadium, and next decision are on the other side.'}</p></div><div className="accessSceneFooter">RUN THE FRANCHISE. <b>OWN THE SEASON.</b></div></section>
    <section className="accessPanel"><div className="accessPanelInner"><p className="accessStep">BIG EXEC ACCOUNT</p><h2>{isSignup?'Create your account.':'Sign in.'}</h2><p className="accessIntro">{isSignup?'Take your seat in the front office.':'Continue building your franchise.'}</p>{params.error&&<p className="errorNotice" role="alert">{params.error}</p>}{params.message&&<p className="successNotice" role="status">{params.message}</p>}<form className="authForm accessForm"><input type="hidden" name="next" value={next}/>{isSignup&&<label>Manager name<input name="display_name" required autoComplete="name" placeholder="How the league will know you"/></label>}<label>Email address<input name="email" type="email" required autoComplete="email" placeholder="you@example.com"/></label><label>Password<input name="password" type="password" minLength={8} required autoComplete={isSignup?'new-password':'current-password'} aria-describedby={isSignup?'password-help':undefined} placeholder="••••••••"/></label>{isSignup&&<div id="password-help" className="passwordHelp"><strong>Secure your front office</strong><span>Use 8+ characters with uppercase, lowercase, a number, and a symbol.</span></div>}{isSignup?<><button className="brandButton gold" formAction={signUp}>Create My Big Exec Account</button><p className="accessSwitch">Already have a seat? <a href={`/login?next=${encodedNext}`}>Sign in</a></p></>:<><button className="brandButton gold" formAction={signIn}>Enter the Front Office</button><p className="accessSwitch">New to Big Exec? <a href={`/login?mode=signup&next=${encodedNext}`}>Create your account</a></p></>}</form><p className="accessLegal">By continuing, you agree to play fair, protect your account, and respect your league.</p></div></section>
  </main>;
}
