import { notFound, redirect } from 'next/navigation';
import { createClient } from '../../../lib/supabase/server';
import { createLeagueInvite, generateCircuitSchedule } from '../actions';
import { initializeDraft } from '../../drafts/actions';
import { FranchiseCrest } from '../../components/FranchiseCrest';
import { SportIdentity } from '../../components/SportIdentity';

type Competition={code?:string|null;display_name?:string|null};
type CompetitionSeason={season_year?:number;competitions?:Competition|Competition[]|null};
function first<T>(value:T|T[]|null|undefined):T|null{return !value?null:Array.isArray(value)?value[0]??null:value;}

export default async function LeaguePage({params,searchParams}:{params:Promise<{leagueId:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const {leagueId}=await params; const query=await searchParams; const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/login');
  const [{data:league},{data:franchises},{data:member},{data:ownerships},{data:leagueSeason},{count:historyCount}]=await Promise.all([
    supabase.from('fantasy_leagues').select('id,name,created_at,draft_min_franchises,max_franchises').eq('id',leagueId).maybeSingle(),
    supabase.from('franchises').select('id,name,abbreviation,primary_color,secondary_color,established_year').eq('league_id',leagueId).order('created_at'),
    supabase.from('league_members').select('role').eq('league_id',leagueId).eq('user_id',user.id).maybeSingle(),
    supabase.from('franchise_owners').select('franchise_id').eq('user_id',user.id).is('ends_on',null),
    supabase.from('league_seasons').select('id,status,competition_seasons(season_year,competitions(code,display_name))').eq('league_id',leagueId).eq('is_current',true).maybeSingle(),
    supabase.from('league_seasons').select('id',{count:'exact',head:true}).eq('league_id',leagueId).eq('status','complete')
  ]);
  if(!league||!member||!leagueSeason) notFound();
  const cs=first(leagueSeason.competition_seasons as CompetitionSeason|CompetitionSeason[]|null); const competition=first(cs?.competitions);
  const ownedIds=new Set((ownerships??[]).map(x=>x.franchise_id)); const myFranchise=(franchises??[]).find(x=>ownedIds.has(x.id));
  const [{data:draft},{count:circuitCount},{data:seasonFranchises},{data:standings},{data:activeMatchup}]=await Promise.all([
    supabase.from('drafts').select('id,status,starts_at,pick_seconds').eq('league_season_id',leagueSeason.id).maybeSingle(),
    supabase.from('matchups').select('id',{count:'exact',head:true}).eq('league_season_id',leagueSeason.id).gte('week',1).lte('week',9),
    supabase.from('season_franchises').select('id,franchise_id').eq('league_season_id',leagueSeason.id),
    supabase.from('standings').select('season_franchise_id,wins,losses,ties,points_for,points_against').eq('league_season_id',leagueSeason.id).order('wins',{ascending:false}).order('points_for',{ascending:false}),
    supabase.from('matchups').select('id,week,home_season_franchise_id,away_season_franchise_id,home_points,away_points,is_final,event_type').eq('league_season_id',leagueSeason.id).order('week',{ascending:false}).limit(1).maybeSingle()
  ]);
  const {data:invites}=member.role==='commissioner'?await supabase.from('league_invites').select('id,email,status,expires_at,invite_token').eq('league_id',leagueId).order('created_at',{ascending:false}):{data:[] as Array<{id:string;email:string;status:string;expires_at:string;invite_token:string}>};
  const memberCount=franchises?.length??0,capacity=league.max_franchises??10,draftMinimum=league.draft_min_franchises??capacity; const draftReady=memberCount>=draftMinimum; const pending=(invites??[]).filter(x=>x.status==='pending').length;
  const appUrl=process.env.NEXT_PUBLIC_APP_URL?.trim()||'https://bigexecfs.com'; const commissioner=member.role==='commissioner'; const draftDate=draft?.starts_at?new Date(draft.starts_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):null;
  const franchiseBySf=new Map((seasonFranchises??[]).map(sf=>[sf.id,(franchises??[]).find(f=>f.id===sf.franchise_id)]));
  return <main className="leagueShell">
    <section className="leagueHero"><div className="leagueHeroGlow"/><div className="leagueTopline"><a className="backLink" href="/dashboard">← FRONT OFFICE</a><span className="leagueRole">{commissioner?'COMMISSIONER':'FRANCHISE MANAGER'}</span></div><div className="leagueHeroContent"><p className="eyebrow">BIG EXEC • LEAGUE HQ</p><h1>{league.name}</h1><p className="leagueTagline">Build the franchise. Run the room. Own the season.</p><div className="leagueMetaRow"><SportIdentity code={competition?.code} displayName={competition?.display_name} compact/><span>{cs?.season_year??'CURRENT'} SEASON</span><span>HALF-PPR</span><span>{memberCount}/{capacity} FRANCHISES</span><span>{draft?.status==='completed'?'DRAFT COMPLETE':draftReady?'DRAFT READY':`${Math.max(0,draftMinimum-memberCount)} TO DRAFT READY`}</span></div><div className="actions"><a className="secondary" href={`/leagues/${leagueId}/history`}>History & Legacy</a><a className="secondary" href={`/leagues/${leagueId}/locker-room`}>Locker Room</a><a className="secondary" href={`/leagues/${leagueId}/players`}>Players</a><a className="secondary" href={`/leagues/${leagueId}/trades`}>Trades</a></div></div></section>
    {query.joined&&<p className="successNotice">Franchise claimed. Welcome to the league.</p>}{query.schedule_status&&<p className="successNotice">The Circuit schedule is ready: Weeks 1–9 are set.</p>}
    {(historyCount??0)>0&&<section className="leagueCommandPanel"><div className="commandHeader"><div><p className="eyebrow">FRANCHISE MEMORY</p><h2>{historyCount} completed season{historyCount===1?'':'s'} travel with this league.</h2></div><span className="commandBadge">PERSISTENT HISTORY</span></div><p className="lede">Titles, rivalry receipts, Redemption wins, Chaos upsets and stadium upgrades remain attached to the franchises that earned them.</p><a className="primary" href={`/leagues/${leagueId}/history`}>Open League History</a></section>}
    <section className="leagueQuickGrid"><article className="leagueStatCard featured"><span>DRAFT STATUS</span><strong>{draft?draft.status.toUpperCase():draftReady?'READY TO SCHEDULE':'BUILDING THE ROOM'}</strong><p>{draftDate?`Draft Day: ${draftDate}`:`${memberCount} of ${draftMinimum} required franchises claimed.`}</p></article><article className="leagueStatCard"><span>FRANCHISES</span><strong>{memberCount}/{capacity}</strong><p>{Math.max(0,capacity-memberCount)} open league slots remain.</p></article><article className="leagueStatCard"><span>HISTORY</span><strong>{historyCount??0}</strong><p>Completed seasons preserved.</p></article></section>
    {draft?.status==='completed'&&<section className="leagueCommandPanel"><div className="commandHeader"><div><p className="eyebrow">SEASON COMMAND</p><h2>Game mode.</h2></div><span className="commandBadge">POST-DRAFT</span></div><div className="commandGrid"><article className="commandCard readyCard"><span>YOUR FRONT OFFICE</span><strong>{myFranchise?.name??'Franchise ready'}</strong><p>Set starters, review your bench, and prepare each weekly lineup.</p>{myFranchise&&<a className="primary" href={`/franchises/${myFranchise.id}/team`}>Manage Team</a>}</article><article className="commandCard readyCard"><span>{activeMatchup?.is_final?`WEEK ${activeMatchup.week} • FINAL`:activeMatchup?`WEEK ${activeMatchup.week} • MATCHUP`:'MATCHUP'}</span><strong>{activeMatchup?`${Number(activeMatchup.home_points).toFixed(2)} – ${Number(activeMatchup.away_points).toFixed(2)}`:'Schedule pending'}</strong><p>{activeMatchup?`${franchiseBySf.get(activeMatchup.home_season_franchise_id)?.name??'Home'} vs ${franchiseBySf.get(activeMatchup.away_season_franchise_id)?.name??'Away'}`:'Your next opponent will appear here when the schedule is set.'}</p>{activeMatchup&&<a className="primary" href={`/matchups/${activeMatchup.id}`}>View Matchup</a>}</article></div></section>}
    {commissioner&&<section className="leagueCommandPanel"><div className="commandHeader"><div><p className="eyebrow">COMMISSIONER COMMAND CENTER</p><h2>Run the current season.</h2></div><span className="commandBadge">BIG EXEC CONTROL</span></div><div className="commandGrid"><article className="commandCard"><span>01 • BUILD THE ROOM</span><strong>{memberCount}/{capacity} franchises claimed</strong><p>Invite managers and fill franchise seats.</p>{query.invite_error&&<p className="errorNotice">{query.invite_error}</p>}{query.invite_created&&query.invite_token&&<div className="inviteLinkBox"><span>INVITE READY FOR {query.invite_email}</span><code>{`${appUrl}/invite/${query.invite_token}`}</code></div>}{memberCount<capacity?<form className="inlineForm" action={createLeagueInvite}><input type="hidden" name="league_id" value={leagueId}/><input name="email" type="email" required placeholder="manager@example.com"/><button className="primary">Send Invite</button></form>:<p className="successNotice">League full. All {capacity} franchise spots are claimed.</p>}</article><article className={`commandCard ${draftReady?'readyCard':''}`}><span>02 • SET DRAFT DAY</span><strong>{draft?'Draft room created':draftReady?'Ready to schedule':`Need ${Math.max(0,draftMinimum-memberCount)} more`}</strong>{query.draft_error&&<p className="errorNotice">{query.draft_error}</p>}{draft?<><p>{draftDate?`Scheduled for ${draftDate}.`:`Draft status: ${draft.status}.`}</p><a className="primary" href={`/drafts/${draft.id}`}>Enter Draft Room</a></>:draftReady?<form className="authForm compactForm" action={initializeDraft}><input type="hidden" name="league_id" value={leagueId}/><label>Draft date & time<input name="starts_at" type="datetime-local"/></label><label>Seconds per pick<input name="pick_seconds" type="number" min="30" max="300" defaultValue="90"/></label><button className="primary">Randomize Order + Create Draft</button></form>:<p>Draft setup unlocks automatically at {draftMinimum} claimed franchises.</p>}</article></div></section>}
    <section className="leagueRosterSection"><div className="sectionTitleRow"><div><p className="eyebrow">FRANCHISE FLOOR</p><h2>The league.</h2></div><span className="sectionCounter">{memberCount}/{capacity}</span></div><div className="franchiseGrid">{(franchises??[]).map((f,index)=>{const mine=ownedIds.has(f.id);const card=<article className={`franchiseCard ${mine?'myFranchise':''}`} style={{'--team-primary':f.primary_color??'#d9b43b','--team-secondary':f.secondary_color??'#f5f1e8'} as React.CSSProperties}><div className="franchiseCardTop"><span>{mine?'YOUR FRANCHISE':`SEAT ${String(index+1).padStart(2,'0')}`}</span><b>{f.abbreviation??'BEX'}</b></div><FranchiseCrest className="franchiseMonogram franchiseCardCrest" name={f.name} abbreviation={f.abbreviation} primary={f.primary_color} secondary={f.secondary_color} decorative/><strong>{f.name}</strong><p>EST. {f.established_year??new Date().getFullYear()}</p>{mine&&<em>ENTER TEAM HQ →</em>}</article>;return mine?<a key={f.id} href={`/franchises/${f.id}/team`}>{card}</a>:<div key={f.id}>{card}</div>})}</div></section>
    {!!standings?.length&&<section className="panel"><p className="eyebrow">CURRENT STANDINGS</p><h2>League table.</h2><div className="standingsList">{standings.map((row,index)=>{const f=franchiseBySf.get(row.season_franchise_id);return <div className="standingRow" key={row.season_franchise_id}><b>{index+1}</b><span>{f?.name??'Franchise'}</span><small>{row.wins}-{row.losses}{row.ties?`-${row.ties}`:''}</small><small>PF {Number(row.points_for).toFixed(2)}</small></div>})}</div></section>}
    {commissioner&&capacity===10&&memberCount===10&&<section className="panel"><p className="eyebrow">SEASON SCHEDULE</p><h2>{circuitCount===45?'The Circuit is set.':'Build Weeks 1–9.'}</h2>{query.schedule_error&&<p className="errorNotice">{query.schedule_error}</p>}{circuitCount===45?<p className="successNotice">45 head-to-head matchups generated.</p>:<form action={generateCircuitSchedule}><input type="hidden" name="league_id" value={leagueId}/><button className="primary">Generate The Circuit</button></form>}</section>}
  </main>;
}
