import { notFound, redirect } from 'next/navigation';
import { loadFantasyEligibleAthletes } from '../../../../lib/fantasy/athletePool';
import { createClient } from '../../../../lib/supabase/server';
import { claimFreeAgent, submitWaiverClaim, withdrawWaiverClaim } from './actions';

const POSITIONS=['ALL','QB','RB','WR','TE','K','D/ST'] as const;
type AthleteTeam={abbreviation?:string}; type Franchise={name?:string;abbreviation?:string}; type Athlete={display_name?:string;position?:string}; type Team={display_name?:string;abbreviation?:string};
type Hold={id:string;athlete_id:string|null;real_team_id:string|null;clears_at:string;status:string};
function first<T>(value:T|T[]|null|undefined):T|null{return !value?null:Array.isArray(value)?value[0]??null:value;}

export default async function PlayersPage({params,searchParams}:{params:Promise<{leagueId:string}>;searchParams:Promise<{position?:string;q?:string;transaction_status?:string;transaction_error?:string;waiver_status?:string;waiver_error?:string}>}){
  const {leagueId}=await params; const query=await searchParams; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/login');
  const [{data:league},{data:member},{data:season},{data:ownerships}]=await Promise.all([
    supabase.from('fantasy_leagues').select('name').eq('id',leagueId).maybeSingle(),
    supabase.from('league_members').select('role').eq('league_id',leagueId).eq('user_id',user.id).maybeSingle(),
    supabase.from('league_seasons').select('id,competition_season_id,roster_config,waiver_period_hours').eq('league_id',leagueId).eq('is_current',true).maybeSingle(),
    supabase.from('franchise_owners').select('franchise_id').eq('user_id',user.id).is('ends_on',null)
  ]); if(!league||!member||!season)notFound();
  const [{data:competitionSeason},{data:sfs},{data:holds}]=await Promise.all([
    supabase.from('competition_seasons').select('competition_id').eq('id',season.competition_season_id).maybeSingle(),
    supabase.from('season_franchises').select('id,franchise_id,franchises(name,abbreviation)').eq('league_season_id',season.id),
    supabase.from('waiver_holds').select('id,athlete_id,real_team_id,clears_at,status').eq('league_season_id',season.id).eq('status','open')
  ]);
  const sfIds=(sfs??[]).map(sf=>sf.id); const ownedFranchiseIds=new Set((ownerships??[]).map(row=>row.franchise_id)); const mySf=(sfs??[]).find(sf=>ownedFranchiseIds.has(sf.franchise_id));
  const rosterPromise=sfIds.length?supabase.from('roster_entries').select('id,season_franchise_id,athlete_id,real_team_id,athletes(display_name,position),real_teams(display_name,abbreviation)').in('season_franchise_id',sfIds).is('dropped_at',null):Promise.resolve({data:[] as Array<{id:string;season_franchise_id:string;athlete_id:string|null;real_team_id:string|null;athletes:Athlete|null;real_teams:Team|null}>,error:null});
  const claimsPromise=mySf?supabase.from('waiver_claims').select('id,waiver_hold_id,status,drop_roster_entry_id,created_at').eq('season_franchise_id',mySf.id).eq('status','pending'):Promise.resolve({data:[] as Array<{id:string;waiver_hold_id:string;status:string;drop_roster_entry_id:string|null;created_at:string}>,error:null});
  const [{data:rosters,error:rosterError},{data:athletes,error:athleteError},{data:teams,error:teamError},{data:claims,error:claimError}]=await Promise.all([
    rosterPromise,loadFantasyEligibleAthletes(supabase),competitionSeason?.competition_id?supabase.from('real_teams').select('id,display_name,abbreviation').eq('competition_id',competitionSeason.competition_id).order('abbreviation'):Promise.resolve({data:[],error:null}),claimsPromise
  ]);
  const loadError=rosterError?.message||athleteError?.message||teamError?.message||claimError?.message; const franchiseBySf=new Map((sfs??[]).map(sf=>[sf.id,first(sf.franchises as Franchise|Franchise[]|null)])); const athleteOwner=new Map<string,string>(),teamOwner=new Map<string,string>();
  for(const row of rosters??[]){const owner=franchiseBySf.get(row.season_franchise_id)?.abbreviation??franchiseBySf.get(row.season_franchise_id)?.name??'ROSTERED';if(row.athlete_id)athleteOwner.set(row.athlete_id,owner);if(row.real_team_id)teamOwner.set(row.real_team_id,owner);}
  const holdByAthlete=new Map((holds??[]).filter(h=>h.athlete_id).map(h=>[h.athlete_id,h as Hold])); const holdByTeam=new Map((holds??[]).filter(h=>h.real_team_id).map(h=>[h.real_team_id,h as Hold])); const claimByHold=new Map((claims??[]).map(c=>[c.waiver_hold_id,c]));
  const requested=(query.position??'ALL').toUpperCase(),active=POSITIONS.includes(requested as typeof POSITIONS[number])?requested:'ALL',q=(query.q??'').trim().toLowerCase(); const filtered=(athletes??[]).filter(a=>(active==='ALL'||a.position===active)&&active!=='D/ST').filter(a=>!q||a.display_name.toLowerCase().includes(q)); const filteredTeams=(teams??[]).filter(t=>(active==='ALL'||active==='D/ST')&&(!q||`${t.abbreviation??''} ${t.display_name??''}`.toLowerCase().includes(q)));
  const myRoster=(rosters??[]).filter(row=>row.season_franchise_id===mySf?.id); const starterCount=Object.values((season.roster_config as {starters?:Record<string,number>}|null)?.starters??{}).reduce((sum,value)=>sum+Number(value),0),rosterLimit=starterCount+Number((season.roster_config as {bench?:number}|null)?.bench??0),rosterFull=myRoster.length>=rosterLimit;
  const dropLabel=(row:typeof myRoster[number])=>row.athlete_id?`${first(row.athletes as Athlete|Athlete[]|null)?.position??''} • ${first(row.athletes as Athlete|Athlete[]|null)?.display_name??'Player'}`:`D/ST • ${first(row.real_teams as Team|Team[]|null)?.abbreviation??first(row.real_teams as Team|Team[]|null)?.display_name??'Defense'}`;
  const assetControl=(asset:{athleteId?:string;realTeamId?:string},hold?:Hold)=>{if(!mySf)return <span className="freeAgentUnavailable">NO FRANCHISE</span>;if(hold){const existing=claimByHold.get(hold.id);if(existing)return <div className="freeAgentClaim"><b className="rosteredStatus">CLAIMED</b><small>Clears {new Date(hold.clears_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small><form action={withdrawWaiverClaim}><input type="hidden" name="league_id" value={leagueId}/><input type="hidden" name="waiver_claim_id" value={existing.id}/><input type="hidden" name="position" value={active}/><button className="miniAction">Withdraw</button></form></div>;return <details className="freeAgentClaim"><summary>CLAIM</summary><form action={submitWaiverClaim}><input type="hidden" name="league_id" value={leagueId}/><input type="hidden" name="season_franchise_id" value={mySf.id}/><input type="hidden" name="waiver_hold_id" value={hold.id}/><input type="hidden" name="position" value={active}/><p className="lede">Waivers clear {new Date(hold.clears_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}. Lower-ranked franchises receive priority when claims process.</p><label>{rosterFull?'Choose a player to drop':'Optional drop if claim wins'}<select name="drop_roster_entry_id" required={rosterFull}><option value="">{rosterFull?'Select from your roster':'No drop needed'}</option>{myRoster.map(row=><option key={row.id} value={row.id}>{dropLabel(row)}</option>)}</select></label><button className="primary">Submit Waiver Claim</button></form></details>;}return <details className="freeAgentClaim"><summary>ADD</summary><form action={claimFreeAgent}><input type="hidden" name="league_id" value={leagueId}/><input type="hidden" name="season_franchise_id" value={mySf.id}/><input type="hidden" name="position" value={active}/>{asset.athleteId&&<input type="hidden" name="athlete_id" value={asset.athleteId}/>} {asset.realTeamId&&<input type="hidden" name="real_team_id" value={asset.realTeamId}/>}<label>{rosterFull?'Choose a player to drop':'Optional: drop a player'}<select name="drop_roster_entry_id" required={rosterFull}><option value="">{rosterFull?'Select from your roster':'No drop needed'}</option>{myRoster.map(row=><option key={row.id} value={row.id}>{dropLabel(row)}</option>)}</select></label><button className="primary">Confirm Add</button></form></details>;};
  return <main><section className="leagueHero" style={{minHeight:320}}><div className="leagueHeroGlow"/><div className="leagueTopline"><a className="backLink" href={`/leagues/${leagueId}`}>← LEAGUE HQ</a><span className="leagueRole">PLAYER INDEX</span></div><div className="leagueHeroContent"><p className="eyebrow">BIG EXEC • {league.name}</p><h1>Players.</h1><p className="leagueTagline">Free agents move immediately. Dropped players spend {season.waiver_period_hours??48} hours on waivers before standings-priority claims clear.</p><div className="leagueMetaRow"><span>QB / RB / WR / TE / K</span><span>D/ST</span><span>{holds?.length??0} ON WAIVERS</span></div></div></section>
    {loadError&&<p className="errorNotice">Player status could not be fully loaded: {loadError}</p>}{query.transaction_status==='added'&&<p className="successNotice">Free agent added to your roster.</p>}{query.transaction_error&&<p className="errorNotice">{query.transaction_error}</p>}{query.waiver_status==='claimed'&&<p className="successNotice">Waiver claim submitted. Priority is determined when the waiver period closes.</p>}{query.waiver_status==='withdrawn'&&<p className="successNotice">Waiver claim withdrawn.</p>}{query.waiver_error&&<p className="errorNotice">{query.waiver_error}</p>}
    <section className="panel"><form className="inlineForm" method="get"><input name="q" defaultValue={query.q??''} placeholder="Search player or team"/><input type="hidden" name="position" value={active}/><button className="secondary">Search</button></form><div className="actions">{POSITIONS.map(pos=><a key={pos} className={active===pos?'primary':'secondary'} href={`?position=${encodeURIComponent(pos)}${query.q?`&q=${encodeURIComponent(query.q)}`:''}`}>{pos}</a>)}</div></section>
    {active!=='D/ST'&&<section className="panel"><p className="eyebrow">INDIVIDUAL PLAYERS</p><div className="playerList">{filtered.map(a=>{const team=first(a.real_teams as AthleteTeam|AthleteTeam[]|null),owner=athleteOwner.get(a.id),hold=holdByAthlete.get(a.id);return <article className="playerRow" key={a.id}><div><span>{a.position} • {team?.abbreviation??'FA'} • {owner?`ROSTERED: ${owner}`:hold?'WAIVERS':'AVAILABLE'}</span><strong>{a.display_name}</strong></div>{owner?<b className="rosteredStatus">ROSTERED</b>:assetControl({athleteId:a.id},hold)}</article>})}{!filtered.length&&<p className="lede">No players match this filter.</p>}</div></section>}
    {(active==='ALL'||active==='D/ST')&&<section className="panel"><p className="eyebrow">D/ST</p><div className="playerList">{filteredTeams.map(t=>{const owner=teamOwner.get(t.id),hold=holdByTeam.get(t.id);return <article className="playerRow" key={t.id}><div><span>D/ST • {owner?`ROSTERED: ${owner}`:hold?'WAIVERS':'AVAILABLE'}</span><strong>{t.abbreviation??t.display_name} D/ST</strong></div>{owner?<b className="rosteredStatus">ROSTERED</b>:assetControl({realTeamId:t.id},hold)}</article>})}</div></section>}
  </main>;
}
