import { notFound, redirect } from 'next/navigation';
import { createClient } from '../../../lib/supabase/server';

export default async function RecapPage({params}:{params:Promise<{recapId:string}>}) {
  const {recapId}=await params;
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user) redirect('/login');
  const {data:script}=await supabase.from('recap_scripts').select('id,title,summary,matchup_id,league_season_id,winner_season_franchise_id,loser_season_franchise_id').eq('id',recapId).maybeSingle();
  if(!script) notFound();
  const {data:scenes}=await supabase.from('recap_scenes').select('scene_index,scene_kind,duration_ms,payload').eq('recap_script_id',recapId).order('scene_index');
  const {data:renders}=await supabase.from('recap_renders').select('aspect_ratio,status,storage_key,renderer_provider,bytes,duration_ms,error_message').eq('recap_script_id',recapId).order('aspect_ratio');
  const ready=(renders??[]).filter(render=>render.status==='ready'&&render.storage_key?.startsWith('http'));
  return <main>
    <section className="panel"><p className="eyebrow">BIG EXEC • ARCADE RECAP</p><h1>{script.title}</h1><p className="lede">{script.summary}</p><div className="actions"><a className="secondary" href={`/matchups/${script.matchup_id}`}>← Matchup</a></div></section>
    {!!ready.length&&<section className="panel"><p className="eyebrow">NOW PLAYING</p><h2>The matchup became a moment.</h2><div style={{display:'grid',gridTemplateColumns:ready.length>1?'repeat(auto-fit,minmax(280px,1fr))':'1fr',gap:14}}>{ready.map(render=><article key={render.aspect_ratio} style={{border:'1px solid #3a3327',background:'#0b0c0f',padding:14}}><div style={{display:'flex',justifyContent:'space-between',gap:10,marginBottom:10}}><span className="eyebrow">{render.aspect_ratio} • {render.renderer_provider?.replaceAll('_',' ').toUpperCase()}</span><strong style={{fontSize:'.72rem'}}>READY</strong></div><video controls playsInline preload="metadata" src={render.storage_key??undefined} style={{display:'block',width:'100%',maxHeight:render.aspect_ratio==='9:16'?720:560,background:'#000'}} aria-label={`${script.title} ${render.aspect_ratio} recap`} /></article>)}</div></section>}
    <section className="panel"><p className="eyebrow">DETERMINISTIC STORYBOARD</p><h2>What the game becomes.</h2><div style={{display:'grid',gap:12}}>{(scenes??[]).map(scene=>{const p=scene.payload as Record<string,unknown>;return <article key={scene.scene_index} style={{minHeight:220,border:'1px solid #3a3327',background:'radial-gradient(circle at 80% 20%,rgba(217,180,59,.18),transparent 28%),linear-gradient(145deg,#17130d,#0a0a0b 70%)',padding:24,display:'grid',alignContent:'space-between',overflow:'hidden'}}><div><span className="eyebrow">SCENE {scene.scene_index} • {scene.scene_kind.replaceAll('_',' ').toUpperCase()} • {(scene.duration_ms/1000).toFixed(1)}s</span></div><div>{scene.scene_kind==='stadium_open'&&<><h2 style={{marginBottom:8}}>{String(p.home)} VS {String(p.away)}</h2><p className="lede">Futuristic stadium opening • Week {String(p.week)} • {String(p.event_type).toUpperCase()}</p></>}{scene.scene_kind==='score_reveal'&&<><h2 style={{marginBottom:8}}>{String(p.home_points)} — {String(p.away_points)}</h2><p className="lede">The real fantasy result controls the scoreboard.</p></>}{scene.scene_kind==='arcade_star'&&<><h2 style={{marginBottom:8}}>{String(p.name)}</h2><p className="lede">{String(p.points)} fantasy points • {String(p.effect).replaceAll('_',' ')}</p></>}{scene.scene_kind==='winner_moment'&&<><h2 style={{marginBottom:8}}>{String(p.winner)}</h2><p className="lede">Winner sequence • margin {String(p.margin)} • {String(p.effect).replaceAll('_',' ')}</p></>}{scene.scene_kind==='final_card'&&<><h2 style={{marginBottom:8}}>{String(p.title)}</h2><p className="lede">Final card locks the actual matchup result.</p></>}</div></article>})}</div></section>
    <section className="panel"><p className="eyebrow">VIDEO OUTPUTS</p><h2>Render queue.</h2><div className="leagueQuickGrid">{(renders??[]).map(render=><article className="leagueStatCard" key={render.aspect_ratio}><span>{render.aspect_ratio} • {(render.renderer_provider??'self_hosted').replaceAll('_',' ').toUpperCase()}</span><strong>{render.status.toUpperCase()}</strong><p>{render.status==='ready'?'MP4 ready to watch and share.':render.status==='rendering'?'Big Exec is rendering this video now.':render.status==='failed'?`Render failed: ${render.error_message??'unknown error'}`:'Storyboard is queued for the animation worker.'}</p></article>)}</div></section>
  </main>;
}
